;;; Dependency-free library regression suite: sbcl --script tests/run.lisp
(load (merge-pathnames "../nd-prover.lisp" *load-truename*))
(in-package :nd-prover)

(defvar *test-root* (merge-pathnames "../" *load-truename*))
(defvar *checks* 0)

(defun check (condition control &rest arguments)
  (incf *checks*)
  (unless condition (apply #'error control arguments)))

(defmacro rejects (&body body)
  `(check (handler-case (progn ,@body nil) (error () t))
          "Expected rejection of ~S." ',body))

(defun fixture (&rest rows)
  (let ((proof (make-proof)))
    (dolist (row rows proof)
      (destructuring-bind (depth formula rule &rest citations) row
        (setf (proof-depth proof) depth)
        (emit-line proof (parse-formula formula) rule citations)))))

(defun checked-example (premises conclusion &key (classical t) (depth 16))
  (let* ((premises (mapcar #'parse-formula premises))
         (conclusion (parse-formula conclusion))
         (proof (prove premises conclusion :classical classical :depth depth)))
    (check proof "No proof found for ~S |- ~A." premises conclusion)
    (check (check-proof proof :premises premises :conclusion conclusion :classical classical)
           "Generated proof failed checking.")
    proof))

(defun truth-value (formula valuation)
  ;; Independent semantic oracle; neither search nor checker calls this.
  (etypecase formula
    (bot nil)
    (pred (cdr (assoc (pred-name formula) valuation :test #'string-equal)))
    (neg (not (truth-value (neg-arg formula) valuation)))
    (conj (and (truth-value (conj-left formula) valuation)
               (truth-value (conj-right formula) valuation)))
    (disj (or (truth-value (disj-left formula) valuation)
              (truth-value (disj-right formula) valuation)))
    (impl (or (not (truth-value (impl-left formula) valuation))
              (truth-value (impl-right formula) valuation)))
    (iff* (eql (truth-value (iff*-left formula) valuation)
               (truth-value (iff*-right formula) valuation)))))

(defun entailed-p (premises conclusion)
  (loop for p in '(nil t) always
    (loop for q in '(nil t) always
      (let ((valuation (list (cons "P" p) (cons "Q" q))))
        (or (not (every (lambda (f) (truth-value f valuation)) premises))
            (truth-value conclusion valuation))))))

(defun small-formulas ()
  (let ((atoms (list (pred "P") (pred "Q") +bot+)))
    (append atoms (mapcar #'neg atoms)
            (loop for constructor in (list #'conj #'disj #'impl #'iff*) append
              (loop for left in atoms append
                (loop for right in atoms collect (funcall constructor left right)))))))

(defun test-parser ()
  (dolist (spelling '("(P ∧ Q) → (R ∨ ¬S)" "(P & Q) -> (R v ~S)"
                      "(P and Q) implies (R or not S)"
                      "(P ^ Q) => (R | ~S)" "(P & Q) ⇒ (R ∨ ¬S)"))
    (check (formula= (parse-formula spelling)
                     (impl (conj (pred "P") (pred "Q"))
                           (disj (pred "R") (neg (pred "S")))))
           "Wrong parse for ~S." spelling))
  (dolist (word '("bot" "bottom" "false" "⊥"))
    (check (bot-p (parse-formula word)) "Wrong bottom alias: ~A." word))
  (dolist (word '("<->" "<=>" "iff" "equiv" "↔"))
    (check (iff*-p (parse-formula (format nil "P ~A Q" word)))
           "Wrong biconditional alias: ~A." word))
  (check (formula= (parse-formula "P -> Q -> R")
                   (impl (pred "P") (impl (pred "Q") (pred "R"))))
         "Implication must associate to the right.")
  (check (formula= (parse-formula "~P & Q v R -> S iff T")
                   (iff* (impl (disj (conj (neg (pred "P")) (pred "Q")) (pred "R"))
                               (pred "S")) (pred "T")))
         "Incorrect operator precedence.")
  (dolist (bad '("" " " "P Q" "P ->" "(P" "P)" "P && Q" "P < Q"
                 "forall P" "P(x)" "P = Q" "1" "()" "not"))
    (rejects (parse-formula bad)))
  ;; All nested binary pairings exercise precedence and both associativities.
  (dolist (left (small-formulas))
    (dolist (right (small-formulas))
      (dolist (constructor (list #'conj #'disj #'impl #'iff*))
        (let ((formula (funcall constructor left right)))
          (check (formula= formula (parse-formula (formula-to-string formula)))
                 "Formula does not round-trip: ~S." formula)))))
  (dolist (formula (small-formulas))
    (check (formula= (neg formula) (parse-formula (formula-to-string (neg formula))))
           "Negation does not round-trip."))
  (check (not (equal (search-key (parse-formula "P & (Q & R)") nil)
                     (search-key (parse-formula "(P & Q) & R") nil)))
         "Search keys conflate distinct formula trees.")
  (check (equal (search-key (parse-formula "p")
                            (premise-entries (mapcar #'parse-formula '("P" "q" "P"))))
                 (search-key (parse-formula "P")
                            (premise-entries (mapcar #'parse-formula '("Q" "p")))))
         "Search keys must ignore atom case, context order, and duplicates.")
  (check (not (equal (search-key (pred "P") nil t)
                     (search-key (pred "P") nil nil)))
         "Search keys must distinguish classical and intuitionistic search."))

(defun test-scope-rejections ()
  (dolist (rows
           '(;; Reuse of a closed sibling assumption proves arbitrary Q -> P.
             ((1 "P" "AS") (0 "P -> P" "→I" 1 1)
              (1 "Q" "AS") (1 "P" "R" 1) (0 "Q -> P" "→I" 3 4))
             ;; A deeper line inside a new sibling cannot cite the old sibling.
             ((1 "P" "AS") (0 "P -> P" "→I" 1 1) (1 "Q" "AS")
              (2 "R" "AS") (2 "P" "R" 1) (1 "R -> P" "→I" 4 5)
              (0 "Q -> (R -> P)" "→I" 3 6))
             ;; Endpoints must not belong to nested or sibling subproofs.
             ((1 "P" "AS") (2 "Q" "AS") (0 "P -> Q" "→I" 1 2))
             ((1 "P" "AS") (1 "Q" "AS") (0 "P -> Q" "→I" 1 2))
             ;; An endpoint before the assumption is not in its subproof.
             ((1 "P" "AS") (1 "Q" "AS") (0 "Q -> P" "→I" 2 1))
             ;; An interior line is not the final endpoint.
             ((1 "P" "AS") (1 "P" "R" 1) (0 "P -> P" "→I" 1 1))
             ;; A discharged subproof in a closed outer branch is unavailable.
             ((1 "P" "AS") (2 "Q" "AS") (2 "P" "R" 1)
              (1 "Q -> P" "→I" 2 3) (0 "P -> (Q -> P)" "→I" 1 4)
              (1 "R" "AS") (1 "Q -> P" "→I" 2 3)
              (0 "R -> (Q -> P)" "→I" 6 7))
             ;; Assumptions, premises, and depth changes need proper structure.
             ((0 "P" "AS"))
             ((2 "P" "AS") (0 "P -> P" "→I" 1 1))
             ((0 "P" "PR") (1 "P" "R" 1) (0 "P" "R" 1))
             ((1 "P" "AS") (1 "Q" "PR") (0 "P -> Q" "→I" 1 2))
             ((0 "P" "PR") (0 "P" "R" 1) (0 "Q" "PR"))
             ((-1 "P" "PR"))
             ((1 "P" "AS"))
             ;; Ordinary citations must be previous, existent, and accessible.
             ((0 "P" "PR") (0 "P" "R" 2))
             ((0 "P" "PR") (0 "P" "R" 3))
             ((0 "P" "PR") (0 "P" "R" 0))
             ((0 "P" "PR") (0 "P" "R" "1"))
             ((1 "P" "AS") (0 "P" "R" 1))
             ;; Or-elimination cannot share the same branch twice.
             ((0 "P v P" "PR") (1 "P" "AS") (0 "P" "∨E" 1 2 2 2 2))
             ;; Nor can its right branch use the left branch's conclusion.
             ((0 "P v Q" "PR") (1 "P" "AS") (1 "Q" "AS")
              (1 "P" "R" 2) (0 "P" "∨E" 1 2 2 3 4))))
    (rejects (check-proof (apply #'fixture rows))))
  (rejects (check-proof (make-proof)))
  (let ((proof (fixture '(0 "P" "PR") '(0 "P" "R" 1))))
    (setf (proof-line-number (aref (proof-lines proof) 1)) 1)
    (rejects (check-proof proof)))
  (let ((proof (fixture '(0 "P" "PR"))))
    (setf (proof-line-formula (aref (proof-lines proof) 0)) :not-a-formula)
    (rejects (check-proof proof)))
  ;; Valid siblings, nested discharges, and enclosing-scope reiterations.
  (check (check-proof (fixture '(0 "P v Q" "PR") '(0 "R" "PR")
                              '(1 "P" "AS") '(1 "R" "R" 2)
                              '(1 "Q" "AS") '(1 "R" "R" 2)
                              '(0 "R" "∨E" 1 3 4 5 6)))
         "Valid disjunction elimination rejected.")
  (check (check-proof (fixture '(1 "P" "AS") '(2 "Q" "AS")
                              '(2 "P" "R" 1) '(1 "Q -> P" "→I" 2 3)
                              '(0 "P -> (Q -> P)" "→I" 1 4)))
         "Valid nested proof rejected."))

(defun test-rule-rejections ()
  (dolist (rows
           '(((0 "P" "PR" 1))
             ((0 "P" "PR") (0 "Q" "R" 1))
             ((0 "P" "PR") (0 "Q" "PR") (0 "P & P" "∧I" 1 2))
             ((0 "P & Q" "PR") (0 "Q" "∧E1" 1))
             ((0 "P & Q" "PR") (0 "P" "∧E2" 1))
             ((0 "P -> Q" "PR") (0 "Q" "PR") (0 "P" "→E" 1 2))
             ((1 "P" "AS") (0 "Q -> P" "→I" 1 1))
             ((1 "P" "AS") (0 "~P" "¬I" 1 1))
             ((0 "P" "PR") (0 "~Q" "PR") (0 "bot" "¬E" 1 2))
             ((0 "P" "PR") (0 "Q" "⊥E" 1))
             ((0 "P" "PR") (0 "Q v P" "∨I1" 1))
             ((0 "P" "PR") (0 "P v Q" "∨I2" 1))
             ((0 "P v Q" "PR") (1 "P" "AS") (1 "Q" "AS")
              (0 "P" "∨E" 1 2 2 3 3))
             ((0 "P -> Q" "PR") (0 "Q -> R" "PR") (0 "P iff Q" "↔I" 1 2))
             ((0 "P iff Q" "PR") (0 "Q -> P" "↔E1" 1))
             ((0 "P iff Q" "PR") (0 "P -> Q" "↔E2" 1))
             ((0 "bot" "PR") (1 "~Q" "AS") (1 "bot" "R" 1)
              (0 "P" "RAA" 2 3))
             ((0 "P" "UNKNOWN"))))
    (rejects (check-proof (apply #'fixture rows)))))

(defun test-search ()
  (dolist (case '((("P" "P -> Q") "Q")
                  (("P" "Q") "P") (("P" "p" "Q") "P")
                  (nil "P -> P") (("Q") "P -> Q")
                  (("P" "Q") "P & Q") (("P & Q") "P") (("P & Q") "Q")
                  (("P") "P v Q") (("Q") "P v Q")
                  (("P v Q" "P -> R" "Q -> R") "R")
                  (("P -> Q" "~Q") "~P") (("P" "~P") "bot")
                  (("bot") "Q") (("P -> Q" "Q -> P") "P iff Q")
                  (("P iff Q") "P -> Q") (("P iff Q") "Q -> P")
                  (("~P") "P -> Q")))
    (checked-example (first case) (second case) :classical nil))
  (checked-example nil "P v ~P")
  (let ((proof (checked-example '("~~P") "P")))
    (rejects (check-proof proof :classical nil)))
  (check (null (prove (mapcar #'parse-formula '("~~P")) (pred "P")
                      :classical nil :depth 8))
         "Double negation elimination should need classical reasoning.")
  (check (null (prove nil (pred "P") :depth 6)) "Proved an arbitrary atom.")
  (check (null (prove nil (parse-formula "P -> P") :depth 0))
         "Depth zero should not permit a recursive introduction.")
  (rejects (prove nil (pred "P") :depth -1))
  (let ((proof (checked-example '("P" "Q") "P")))
    (check (string= "R" (proof-line-rule (aref (proof-lines proof) 2)))
           "An earlier premise must be reiterated as the conclusion.")
    (rejects (check-proof proof :premises nil))
    (rejects (check-proof proof :premises (list (pred "P"))))
    (rejects (check-proof proof :premises (list (pred "P") (pred "R"))))
    (rejects (check-proof proof :conclusion (pred "Q"))))
  (dolist (path (directory (merge-pathnames "examples/*.nd" *test-root*)))
    (multiple-value-bind (premises conclusion) (read-problem path)
      (check (prove premises conclusion) "Bundled example failed: ~A." path))))

(defun test-semantic-soundness ()
  (let ((successes 0))
    (dolist (context '(nil ("P") ("Q") ("P" "Q") ("P" "~P")
                        ("P -> Q") ("P v Q") ("P iff Q")))
      (let ((premises (mapcar #'parse-formula context)))
        (dolist (conclusion (small-formulas))
          (dolist (classical '(nil t))
            (let ((proof (prove premises conclusion :depth 4 :classical classical)))
              (when proof
                (incf successes)
                (check (entailed-p premises conclusion)
                       "Semantically invalid proof: ~S |- ~A." context
                       (formula-to-string conclusion))))))))
    (check (> successes 100) "Too few semantic cases exercised: ~D." successes)
    (format t "Truth-table checks covered ~D generated proofs.~%" successes)))

(test-parser)
(test-scope-rejections)
(test-rule-rejections)
(test-search)
(test-semantic-soundness)
(format t "Passed ~D checks.~%" *checks*)
